name: Create and publish a package
on:
  push:
    branches: ['main']
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_REGISTRY }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: server
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
